### ISSUE TITLE
flutter的国密库可以看看dart_sm

### ISSUE THREAD

**Issue by luckykellan** [greenking19/sm_crypto#12]
不知道作者还维不维护，公司业务上需要，我写了一个完整的：[dart_sm](https://github.com/luckykellan/dart_sm)

**Comment by greenking19** [comment]
还在维护的 只是比较懒而已
我看了你的源码 写的不错
谢谢 晚点直接copy😚

**Comment by luckykellan** [comment]
可以，注明出处就好。
另外，你的SM3性能应该有些问题，下面是同样对1m数据做杂凑的耗时
![image](https://user-images.githubusercontent.com/109934256/231079737-40356bd7-778d-467c-819e-b6001877e39f.png)

**Comment by greenking19** [comment]
> 可以，注明出处就好。 另外，你的SM3性能应该有些问题，下面是同样对1m数据做杂凑的耗时 ![image](https://user-images.githubusercontent.com/109934256/231079737-40356bd7-778d-467c-819e-b6001877e39f.png)
哦哦哦 之前做的时候还没有杂凑，谢谢建议 周末我优化一下
